language: python

python:
  - 3.4

install:
  - pip install -r requirements-dev.txt --use-mirrors

script:
  # To run tests without computing cov:
  #   python -m unittest discover -s tests
  # And with cov:
  coverage run --source=koa -m unittest discover -s tests

after_success:
  # Get a simple coverage report without coveralls:
  - coverage report -m koa/common.py koa/core.py
  # And with coveralls:
  - coveralls