language: python

python:
  - 3.4

install:
  - pip install -r requirements-dev.txt --use-mirrors

script:
  # To run tests without computing cov:
  #   python -m unittest discover -s tests
  # And with cov:
  coverage run -m unittest discover -s tests
  coverage report -m